kafka_url = "localhost:9094"
num_threads = 4
debug_level = "debug"

[remoteDetails]
host = "localhost:2222"
username = "testuser"
password = "password"

[locations]
incompletes = "./incompletes/"
completes = "./completes/"

#: Database Settings
[database]
host = "localhost"
port = 5433
user = "ks_user"
password = "ks_password"
dbname = "kafkasync_db"
#  S3 / MinIO Config
[objectStorage]
endpoint = "localhost:9000"
access_key = "minioadmin"
secret_key = "minioadmin"
bucket = "kafkasync-archive"
use_ssl = false
region = "us-east-1"