kafka_url = "localhost:9094"
num_threads = 4
debug_level = "debug"

[remoteDetails]
host = "localhost:2222"
username = "testuser"
password = "password"

[locations]
incompletes = "./incompletes/"
completes = "./completes/"